[package]
name = "vb6format"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Formatter for VB6 source files"
repository.workspace = true
keywords = ["vb6", "formatter", "fmt"]
categories = ["development-tools", "parsing"]

[dependencies]
vb6parse.workspace = true
anyhow.workspace = true
