[package]
name = "aspen"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = """
Aspen, a VB6 tool for parsing and analyzing VB6 code, in the spirit of cargo check, cargo fmt, etc.
"""
repository.workspace = true
readme = "README.md"
keywords = ["vb6", "parser", "analyzer", "vb6parse"]
categories = ["development-tools", "parsing", "parser-implementations"]

[dependencies]
vb6parse.workspace = true
clap.workspace = true
walkdir.workspace = true
anyhow.workspace = true
rayon.workspace = true