#!/usr/bin/env python3
"""Generate the A1/D3 parameter-classification table.

Joins builtin-registry entries (vb6interpret/src/builtins/*.rs) with their
runtime signatures (vb6runtime/src/library/**/*.rs) and classifies each
parameter per plan.md decisions (A1, A2/F1, A8).
"""
import re
from pathlib import Path

ROOT = Path("/home/arthur/Programming/Personal_Projects/vb6")
BUILTINS = ROOT / "projects/vb6interpret/src/builtins"
LIBRARY = ROOT / "projects/vb6runtime/src/library"

PREDICATES = {
    "isarray", "isdate", "isempty", "iserror", "ismissing", "isnull",
    "isnumeric", "isobject", "typename", "vartype",
}
STRUCTURAL_PARAM_NAMES = {"sourcearray", "values", "choices", "valuearray", "array"}
# Names that appear as plain calls inside adapters but are not runtime targets.
NON_TARGET_CALLEES = {
    "map", "ok_or_else", "unwrap_or_else", "with_description", "expect",
    "transpose", "and_then", "as_str", "as_i32",
}
# Manual overrides where naming rules are not enough: (category, name) -> class.
OVERRIDES = {
    ("logic", "iif"): "structural",
    ("string", "string"): "variant-input",
    ("string", "string$"): "variant-input",  # character param propagates Null
}

def parse_registry():
    entries = []
    for path in sorted(BUILTINS.glob("*.rs")):
        if path.name in ("mod.rs", "tests.rs"):
            continue
        category = path.stem
        text = path.read_text().split("#[cfg(test)]")[0]
        alias = None
        m = re.search(r"use vb6runtime::library::\w+ as (\w+);", text)
        if m:
            alias = m.group(1)
        for m in re.finditer(r'(?:typed_)?builtin!\(\s*"([^"]+)",\s*(\d+),\s*(\d+)', text):
            name, mn, mx = m.group(1), int(m.group(2)), int(m.group(3))
            tail = text[m.end():m.end() + 2500]
            target = None
            if alias:
                tm = re.search(
                    re.escape(alias) + r"::(?:\w+::)*(\w+)\s*\(", tail)
                if tm:
                    target = tm.group(1)
            else:
                # Files that import runtime functions directly: first bare
                # call that is not a combinator.
                for bm in re.finditer(r"\b([a-z_]\w*)\s*\(", tail):
                    if bm.group(1) not in NON_TARGET_CALLEES:
                        target = bm.group(1)
                        break
            entries.append((category, name, mn, mx, target))
    return entries

def parse_signatures():
    sigs = {}
    for path in sorted(LIBRARY.rglob("*.rs")):
        text = path.read_text().split("#[cfg(test)]")[0]
        for m in re.finditer(
            r"pub fn (\w+)\s*\(((?:[^()]|\([^)]*\))*?)\)\s*->\s*([^{]+?)\s*\{",
            text, re.S,
        ):
            params = re.sub(r"\s+", " ", m.group(2)).strip().rstrip(",")
            ret = re.sub(r"\s+", " ", m.group(3)).strip()
            sigs.setdefault(m.group(1), (params, ret))
    return sigs

def classify(name, params):
    bare = name.rstrip("$%&!#@").lower()
    if bare in PREDICATES:
        return "predicate", "n/a (observes raw variant)"
    param_list = [p.strip() for p in params.split(",") if p.strip()]
    names = [p.split(":")[0].strip().lstrip("_") for p in param_list]
    has_variant = any(p.endswith("&VBVariant") for p in param_list)
    structural = any(n in STRUCTURAL_PARAM_NAMES for n in names)
    if structural:
        return "structural", "propagates Null"
    # `$` forms are strict regardless of today's runtime signature: the
    # migration target types every parameter (plan A8), so a remaining
    # `&VBVariant` is pending phase-1 work, not a design property.
    if name.endswith("$"):
        return "$-strict", "raises 94"
    if has_variant:
        return "variant-input", "propagates Null"
    return "typed", "raises 94"

def main():
    registry = parse_registry()
    sigs = parse_signatures()
    lines = []
    lines += [
        "# Parameter classification (plan A1/D3 step-zero artifact)",
        "",
        "Generated by `generate_parameter_classification.py` from the builtin",
        "registry joined with runtime signatures; regenerate with:",
        "",
        "    python3 projects/vb6runtime/docs/generate_parameter_classification.py",
        "",
        "See `../plan.md` for the decisions encoded here (A1, A2/F1, A8, B3).",
        "Classes:",
        "",
        "- **typed** — every parameter is a wrapper (`&VBString`, `&VBLong`, ...);",
        "  conversion happens once at the host boundary via `boundary::arg`;",
        "  Null raises error 94 there.",
        "- **variant-input** — non-`$` form whose primary input stays `&VBVariant`",
        "  by design (A8: Variant-returning siblings of `$` forms); auxiliary",
        "  numeric/string parameters are still typed. The function body decides",
        "  Null propagation (F1).",
        "- **$-strict** — `$` form, all parameters typed, Null raises 94.",
        "- **predicate** — observes the un-coerced variant; stays `&VBVariant` (A1).",
        "- **structural** — array/list parameters that are genuinely Variant.",
        "- **statement-form** — executed by `exec::*`, conversions wrapped by",
        "  `error_here` (see table at the bottom).",
        "",
    ]
    missing = []
    by_cat = {}
    for cat, name, mn, mx, target in registry:
        by_cat.setdefault(cat, []).append((name, mn, mx, target))
    counts = {}
    for cat in sorted(by_cat):
        lines += [f"## `{cat}`", "", "| Function | Arity | Runtime signature | Class | Null |", "|---|---|---|---|---|"]
        for name, mn, mx, target in sorted(by_cat[cat]):
            if target and target in sigs:
                params, ret = sigs[target]
            else:
                # No direct runtime target (e.g. `beep` builds its result
                # inline); classify on the registry name alone.
                missing.append((cat, name, target))
                params, ret = "", ""
            if (cat, name) in OVERRIDES:
                cls = OVERRIDES[(cat, name)]
                null = "propagates Null" if "variant" in cls or cls == "structural" else "raises 94"
            else:
                cls, null = classify(name, params)
            counts[cls] = counts.get(cls, 0) + 1
            sig = f"`fn({params}) -> {ret}`" if ret else "*(adapter-built, no runtime target)*"
            lines.append(f"| `{name}` | {mn}..{mx} | {sig} | {cls} | {null} |")
        lines.append("")
    lines += [
        "## Statement forms (exec-wired, not registry dispatch)",
        "",
        "| Statement | Runtime primitive | Boundary conversions in exec | Null |",
        "|---|---|---|---|",
        "| `Date` / `Time` (=) | `date_statement` / `time_statement` | value -> date serial (`as_date_serial`) | raises on bad coerce |",
        "| `LSet` / `RSet` var = s | `lset_statement` / `rset_statement` | both sides -> `VBString` | renders `Error n`, else 94/13 |",
        "| `Mid`/`MidB` target(start[,len]) = s | `mid_statement` / `midb_statement` | start,len -> `VBLong`; strings -> `VBString` | raises on bad coerce |",
        "| `AppActivate title[,wait]` | `app_activate` | title -> string, wait -> bool | renders `Error n` for title |",
        "| `SendKeys keys[,wait]` | `send_keys` | keys -> string, wait -> bool | same |",
        "| `SavePicture pic, file` | `save_picture` | filename -> `VBString` | raises |",
        "| `Open`/`Close`/`Print #`/`Input #`/`Write #` | `exec/file_io.rs` | path/mode/record -> typed forms | raises |",
        "",
        "Statement-form operands arrive as flat token runs; their conversions",
        "live in `vb6interpret/src/exec/*` until the parser emits expression",
        "nodes, and are out of scope for the registry sweep (plan A11).",
        "",
    ]
    if missing:
        lines += ["## Entries without a direct runtime target", "",
                  "Adapter builds the result inline (state reads, constants);",
                  "nothing to migrate at the runtime boundary:", ""]
        for cat, name, target in missing:
            lines.append(f"- `{cat}`:`{name}`")
        lines.append("")
    out = Path(__file__).with_name("parameter-classification.md")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")
    print(f"{len(registry)} registry entries, {len(missing)} unresolved")
    print("class counts:", counts)

if __name__ == "__main__":
    main()
